task: embedding_inference
dataset:
  name: "sln_208_d1"
  path: "/home/aqoku/projects/data/mfl_bench/sln_208_single_batch_d1.h5ad"

model:
  name: "scgpt"
  model_dir: "/home/aqoku/models/scgpt"  # update this path
  gene_col: "index"

runtime:
  batch_size: 64
  device: "cuda"

output:
  dir: "outputs/sln_208_d1_scgpt"
